language: go

go:
  - 1.9
  - master

install: true

notifications:
  email: false

before_script:
  - go env
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - GO_FILES_IGNORE_VENDOR=$(go list ./... | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Badass static analyzer/linter
  - go get github.com/fzipp/gocyclo
  - go get github.com/kardianos/govendor
  - govendor list
  - govendor sync

script:
  # Fail if a .go file hasn't been formatted with gofmt
  - test -z $(gofmt -s -l $GO_FILES)
#  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) && test -z $(gofmt -s -l $GO_FILES)
  # Run all the tests with the race detector enabled
  - go test -v -race  $GO_FILES_IGNORE_VENDOR
      # all tag
  - go test -v -tags all -race  $GO_FILES_IGNORE_VENDOR
      # tag feature1
  - go test -v -tags feature1 -race $GO_FILES_IGNORE_VENDOR
      # tag feature2
  - go test -v -tags feature2 -race $GO_FILES_IGNORE_VENDOR
      # tag feature1 & feature2
  - go test -v -tags="feature1 feature2" -race $GO_FILES_IGNORE_VENDOR
#  - go test -v -race ./..
  - go vet ./...                             # go vet is the official Go static analyzer
  - megacheck ./...                          # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
  - golint -set_exit_status $GO_FILES_IGNORE_VENDOR # one last linter

branches:
  only:
    - golang-test
