language: go

go:
  - 1.9
  - master

install: true

notifications:
  email: false

before_script:
  - go env
  - bash ./sh/before_script.sh

script:
  # Fail if a .go file hasn't been formatted with gofmt
  - test -z $(gofmt -s -l $GO_FILES)
#  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) && test -z $(gofmt -s -l $GO_FILES)
  - bash ./sh/test.sh
#  - go test -v -race ./..
  - go vet ./...                             # go vet is the official Go static analyzer
  - megacheck ./...                          # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
  - golint -set_exit_status $(go list ./...) # one last linter

branches:
  only:
    - golang-test
